new cookieNoticeJS({
    messageLocales: {
        at: "Die Website verwendet Cookies u.a. zur Erbringung von Dienstleistungen und zur Erstellung von Statistiken. Die Nutzung der Website ohne Änderung der Einstellungen bedeutet, dass Sie die Verwendung von Cookies akzeptieren.",
        cs: "Webové stránky používají soubory cookie mimo jiné k poskytování služeb a k sestavování statistik. Používání stránek bez změny nastavení znamená, že souhlasíte s používáním souborů cookie.",
        de: "Die Website verwendet Cookies u.a. zur Erbringung von Dienstleistungen und zur Erstellung von Statistiken. Die Nutzung der Website ohne Änderung der Einstellungen bedeutet, dass Sie die Verwendung von Cookies akzeptieren.",
        et: "Veebileht kasutab küpsiseid, sh teenuste osutamiseks ja statistika kogumiseks. Veebilehte, ilma seadeid muutmata kasutades, nõustud küpsistega.",
        es: "El sitio web utiliza cookies, entre otras cosas, para prestar servicios y elaborar estadísticas. Utilizar el sitio sin cambiar la configuración significa que usted acepta el uso de cookies.",
        fi: "Sivusto käyttää evästeitä mm. tarjotakseen palveluja ja laatiakseen tilastoja. Käyttämällä verkkosivustoa muuttamatta asetuksia Käyttäjä hyväksyy evästeiden käytön.",
        fr: "Le site utilise des cookies, notamment dans le but de fournir des services et d'établir des statistiques. En utilisant le site Web sans modifier les paramètres, vous acceptez l'utilisation de cookies.",
        hr: "Web stranica koristi kolačiće, uključujući za pružanje usluga i sastavljanje statistike. Korištenjem web stranice bez promjene postavki prihvaćate korištenje kolačića.",
        hu: "A weboldal többek között a szolgáltatások nyújtása és a statisztikák összeállítása érdekében cookie-kat használ. A weboldal használata a beállítások megváltoztatása nélkül azt jelenti, hogy Ön elfogadja a sütik használatát.",
        it: "Il sito web utilizza i cookie, tra l'altro, per fornire servizi e compilare statistiche. L'utilizzo del sito senza modificare le impostazioni implica l'accettazione dell'uso dei cookie.",
        "fr-BE": "Le site utilise des cookies, notamment dans le but de fournir des services et d'établir des statistiques. En utilisant le site Web sans modifier les paramètres, vous acceptez l'utilisation de cookies.",
        lt: "Svetainėje naudojami slapukai, siekiant teikti paslaugas ir rengti statistiką. Naudodamiesi svetaine nekeisdami nustatymų, sutinkate su slapukų naudojimu.",
        lv: "Vietne izmanto sīkdatnes, t.sk lai sniegtu pakalpojumus un apkopotu statistiku. Izmantojot vietni, nemainot iestatījumus, Jūs piekrītat sīkdatņu izmantošanai.",
        nl: "De website gebruikt cookies onder andere om diensten te verlenen en statistieken op te stellen. Als je de site gebruikt zonder je instellingen te wijzigen, betekent dit dat je het gebruik van cookies aanvaardt.",
        "nl-BE": "De website gebruikt cookies onder andere om diensten te verlenen en statistieken op te stellen. Als je de site gebruikt zonder je instellingen te wijzigen, betekent dit dat je het gebruik van cookies aanvaardt.",
        pl: "Strona używa plików cookies m.in. w celu świadczenia usług oraz opracowywania statystyk. Korzystanie z witryny bez zmiany ustawień oznacza akceptację korzystania z plików cookies.",
        pt: "O website utiliza cookies, entre outras coisas, para fornecer serviços e para compilar estatísticas. Utilizar o site sem alterar as definições significa que aceita a utilização de cookies.",
        ro: "Site-ul utilizează module cookie, printre altele, pentru a furniza servicii și pentru a întocmi statistici. Utilizarea site-ului fără a modifica setările înseamnă că acceptați utilizarea modulelor cookie.",
        sl: "Spletno mesto med drugim uporablja piškotke za zagotavljanje storitev in zbiranje statističnih podatkov. Uporaba spletnega mesta brez spremembe nastavitev pomeni, da se strinjate z uporabo piškotkov.",
        sk: "Webové stránky používajú súbory cookie okrem iného na poskytovanie služieb a zostavovanie štatistík. Používanie stránky bez zmeny nastavení znamená, že súhlasíte s používaním súborov cookie.",
    },
    buttonLocales: {
        at: "Akzeptieren",
        cs: "Přijmout",
        de: "Akzeptieren",
        et: "Nõustu",
        es: "Aceptar",
        fi: "Hyväksy",
        fr: "Accepter",
        "fr-BE": "Accepter",
        hr: "Prihvatit",
        hu: "Elfogadom",
        it: "Accettare",
        lt: "Sutikti",
        lv: "Pieņemt",
        nl: "Accepteren",
        "nl-BE": "Accepteren",
        pl: "Akceptuj",
        pt: "Aceitar",
        ro: "Acceptă",
        sl: "Sprejmite",
        sk: "Prijať",
    },
});